### ISSUE TITLE
Hi, Why is the space amplification of Jungle bigger than Tiering?

### ISSUE THREAD

**Issue by zjs1224522500** [eBay/Jungle#147]
- Firstly, Jungle is an excellent work. Thanks for your efforts~
- I have a question after reading the paper. **Why is the space amplification of Jungle bigger than Tiering?**
  - From previous analysis, the space amplification of Jungle may be similar to that of Tiering. However, the evaluation result shows that the space amplification of Jungle when C=5 or C=10 is bigger than tiering. And the fluctuation of space amplication seems also bigger than tiering. I am confused about this. 

![image](https://user-images.githubusercontent.com/17877010/204491505-ce75544d-4b6e-4b3c-9888-71c30341b644.png)

**Comment by greensky00** [comment]
Please refer to the 4th paragraph of Section 4 in the paper. The size of sorted runs (SSTables) is not even, so if there are 10 SSTable for the same key range, the aggregated size is not 10x of leveling; it is averaged out to ~3.3. 

The same thing also happens in Jungle; batch size is not even. But, Jungle triggers inter-level merge based on the actual size, not the number of batches. So it is closer to the expected size (10x for C=10) than tiering.

Page 57 and 58 in this [slide](https://www.usenix.org/sites/default/files/conference/protected-files/hotstorage19_slides_ahn.pdf) visualize it.

**Comment by zjs1224522500** [comment]
Got it~ Thanks for your reply!
